name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, bcmath, intl

      - name: Install Composer deps
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install NPM deps & build
        run: |
          npm install
          npm run build

      - name: Prepare deployment
        run: |
          mkdir deploy
           rsync -av --progress \
           app bootstrap config database public resources routes \
           deploy/ --exclude=node_modules --exclude=vendor --exclude=tests


      - name: Deploy to Hostinger via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./deploy/
          server-dir: /domains/personal-financely.es/public_html/

      - name: Run Composer and optimize on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /domains/personal-financely.es/public_html/
            composer2 install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
